# Qu'est-ce que la recherche de trajets ?

C'est la recherche d'un trajet qui permet d'aller d'un point A à un point B au travers d'une carte.

Les algorithmes que nous allons voir aujourd'hui sont les suivants.

1. Recherche profondeur d'abord (DFS)
2. Recherche Largeur d'abord (BFS)
3. Recherche par heuristique avec A* 

Pour avoir une bonne intuition sur ces algorithmes ouvre [ce lien](https://pathfindout.com/).

### Se déplacer en voiture au Québec

![Villes de la province de Québec](images/TSPquebec.png "Villes de la province de Québec")

Original de l'image disponible à https://freevectormaps.com/canada/quebec/CA-QC-EPS-01-0001?ref=atr


# Représantation d'une carte 2D en python

Il existe beaucoups de manières de représenter une carte en python. 

- Un tableau de valeurs en python. (numpy)
- Une liste de tuples
- Une double liste
- Un dictionnaire
- Etc.

Par exemple une carte de 10 en Y à la verticale et 10 en X à l'horizontal peut facilement être écrite en python comme suit:

In [61]:
import numpy as np

# Ici, Y est en premier et représente les lignes et X est en deuxième représentant les colonnes
carte = np.zeros((11, 11))
print(carte)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Par la suite on peut manuellement ajouter des information pour chaque point en changeant des informations contenu dans le tableau. 

Par exemple, si on veut dire que le point de départ est à Y = 0 et X = 0 on peut assigner la valeur 1 comme suit:

In [ ]:
carte[0, 0] = 1
print(carte)

Si on veut ajouter un point d'arrivé à Y = 7, X = 9, on peut assigner la valeur 2 comme suit:

In [ ]:
carte[7, 9] = 2
print(carte)

Si on veut ajouter des obstacles dans la colone du centre de la carte, on peut assigner la valeur 3 comme suit:

In [ ]:
carte[:, 5] = 3
print(carte)

De même que si on veut ajouter des obstacles dans la ligne du centre, on peut assigner la valeur 3 comme suit:

In [ ]:
carte[5, :] = 3
print(carte)

Maintenant si on veut ajouter des obstacles aléatoires dans la carte, on peut assigner la valeur 4 comme suit:

In [ ]:
# Il se peut que l'obstacle aléatoire soit généré par dessus un autre dans la carte!
random_Y = np.random.randint(0, 11)
random_X = np.random.randint(0, 11)
carte[random_Y, random_X] = "4"
print(carte)

Dans si on veut en ajouter 10 obstacles avec la valeur 5 ça donne :

In [63]:
for i in range(10):
    random_Y = np.random.randint(0, 11)
    random_X = np.random.randint(0, 11)
    carte[random_Y, random_X] = 5
print(carte)

[[0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]]


## ❗ RAPPEL : Peut-on ajouter ou lire une valeur à l'index 11, 11 ?

In [ ]:
carte[11, 11] = 6
print(carte[11, 11])

## Représentation `Grid2D`, `Node` et `Vector2D`

Pour sauver la Ronde 2.0 et ses robots, il faudrat se familiariser avec la représentation de la carte.
Dans l'ancien code de la Ronde 2.0 qu'il vous faudra réparer, deux structures de données sont très importantes pour les robots.


#### 1. Classe `Vector2D`

##### **Description:**
Le rôle de la classe `Vector2D` est de représenter un point **x** et **y** dans la carte des robots.

##### **Attributs:**
- `x` : La coordonnée horizontale du point.
- `y` : La coordonnée verticale du point.

##### **Méthodes importantes:**
Plusieurs méthode sont déjà écrite qui vous permettent d'additionner, soustraire, multiplier et diviser deux points entre eux.
La méthode la plus importante pour les robots est celle qui permet le calcul de la distance entre deux points.

1. **Distance entre deux points:**

    La méthode `distance_from(Vector2D)` permet de calculer la **distance entre deux points** dans la carte :
    
    ${distance} = \sqrt{(\Delta x)^2 + (\Delta y)^2}$

    qui est l'équivalent de :

    ${distance} = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$

    La méthode s'applique à un point `Vector2D` et prend en paramètre un autre point `Vector2D`.

    Par exemple en code ça donne:  
    ```python
    point1 = Vector2D(0, 0)
    point2 = Vector2D(3, 4)
    print(point1.distance_from(point2))  # Résultat : 5.0
    ```

In [ ]:
# Affiche la distance entre un point en x = 23, y = 42 et un autre en x = 331, y = 71
point1 = Vector2D(23, 42)
point2 = Vector2D(331, 71)
print(point1.distance_from(point2))

# C'est trop facile ? affiche la distance entre deux points généré aléatoirement:
point1 = Vector2D(random.randint(1000), random.randint(1000))
point2 = Vector2D(random.randint(1000), random.randint(1000))
print(f"La distance entre les points {point1} et {point2} est {point1.distance_from(point2)}")

#### 1. Classe `Node`

##### **Description:**
Le rôle de la classe `Node` est de représenter un cercle autour d'un point central **x** et **y** dans la carte des robots.
Cette zone peut être occupée ou libre, indiquant ainsi si elle contient d'autres robots, des manèges ou bien des visiteurs.

##### **Attributs:**
- `center` : Les coordonnées centrales du cercle défini par un objets `Vector2D`.
- `radius` : Le rayon du cercle.
- `was_occupied` : Indique si le cercle était occupé.
- `occupants` : Liste des choses qui sont dans le cercle.

##### **Méthodes importantes:**
Plusieurs méthode sont déjà écrite qui vous permettent d'obtenir le diamètre du cercle ou la diagonale du carré dans lequel le cercle rentre.
La méthode la plus importante dans pour les robots est celle qui évalue si on peut marcher dans cette zone.

1. **Peux t'on marcher dans ce cercle:**

    La méthode `walkable()` permet de savoir si **l'on marcher dans ce cercle**. 
    Autrement dit 
    
    ${distance} = \sqrt{(\Delta x)^2 + (\Delta y)^2}$

    qui est l'équivalent de :

    ${distance} = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$

    La méthode s'applique à un point `Vector2D` et prend en paramètre un autre point `Vector2D`.

    Par exemple en code ça donne:  
    ```python
    point1 = Vector2D(0, 0)
    point2 = Vector2D(3, 4)
    print(point1.distance_from(point2))  # Résultat : 5.0
    ```

##### Grid2 Liste of Nodes.

# Crée ton labyrinthe!

In [89]:
# based on https://inventwithpython.com/recursion/chapter11.html
import numpy as np
from IPython.display import HTML, display
import time

# Défini la taille du labyrinthe minimum 3x3 et impair
TAILLE_Y = 11
TAILLE_X = 21

assert TAILLE_Y % 2 == 1 and TAILLE_Y >= 3
assert TAILLE_X % 2 == 1 and TAILLE_X >= 3

# Permet de regénérer le même labyrinthe
import random
# SEED = 2
# random.seed(SEED)

VIDE = '⬜'
MUR = '🟦'
DEBUT = '🟩'
FIN = '🟥'
PACMAN = '😼'
VISITEE = '🟨'
CHEMIN = '🔳'
NORD, SUD, EST, OUEST = 'n', 's', 'e', 'o'

# On rempli un tableau numpy avec des murs partout
labyrinthe = np.full((TAILLE_Y, TAILLE_X), MUR)

chaine_labyrinthe = '<br>'.join(''.join(row) for row in labyrinthe)
display(HTML(f'''
    <div id="maze" style="font-family: monospace; white-space: pre; line-height: 1.2;">
    {chaine_labyrinthe}
    </div>
    <script>
    document.getElementById('maze').innerHTML = `{chaine_labyrinthe}`;
    </script>
    '''))

def afficherLabyrinthe(labyrinthe, x, y, cases_visitees):
    for c in cases_visitees:
      labyrinthe[int(c.y), int(c.x)] = VISITEE

    if (x, y) != (0, 0):
      labyrinthe[y, x] = PACMAN

    chaine_labyrinthe = '<br>'.join(''.join(ligne) for ligne in labyrinthe)

    html = f'''
    <script>
    document.getElementById('maze').innerHTML = `{chaine_labyrinthe}`;
    </script>
    '''

    display(HTML(html))


# Fonction qui génère le labyrinthe aléatoirement
def genererLabyrinthe(x, y):
  labyrinthe[y, x] = VIDE
  afficherLabyrinthe(labyrinthe.copy(), x, y, [])

  voisins_non_visites = []
  while True:
    if y > 1 and (x, y - 2) not in cases_visitees:
      voisins_non_visites.append(NORD)
    if y < TAILLE_Y - 2 and (x, y + 2) not in cases_visitees:
      voisins_non_visites.append(SUD)
    if x < TAILLE_X - 2 and (x + 2, y) not in cases_visitees:
      voisins_non_visites.append(EST)
    if x > 1 and (x - 2, y) not in cases_visitees:
      voisins_non_visites.append(OUEST)


    if len(voisins_non_visites) == 0:
      # dead end
      break
    else:
      # Recursion
      prochain_noeud = random.choice(voisins_non_visites)
      if prochain_noeud == NORD:
        labyrinthe[y - 1, x] = VIDE
        y -= 2
      elif prochain_noeud == SUD:
        labyrinthe[y + 1, x] = VIDE
        y += 2
      elif prochain_noeud == EST:
        labyrinthe[y, x + 1] = VIDE
        x += 2
      elif prochain_noeud == OUEST:
        labyrinthe[y, x - 1] = VIDE
        x -= 2
      cases_visitees.append((x, y))
      voisins_non_visites = []
      genererLabyrinthe(x, y)



cases_visitees = [(1, 1)]
genererLabyrinthe(1, 1)

labyrinthe[1, 1] = DEBUT
labyrinthe[-2, -2] = FIN
afficherLabyrinthe(labyrinthe.copy(), 0, 0, [])





# ADD : Clone project to colab and pip install requirements

# Add the project root (ai-park) to the Python path
import sys
from pathlib import Path
project_root = Path.cwd().parent.parent  # Goes up from workshop_0 -> examples -> ai-park
sys.path.insert(0, str(project_root))

from park.logic.grid import Grid2D
from park.logic.node import Node
from park.internal.collider import BoxCollider

grid = Grid2D(TAILLE_X, TAILLE_Y, 1.0)
print(len(grid.nodes), len(grid.nodes[0]))
print(labyrinthe.shape)

print(int(grid.nodes[0][0].center.x))
print(grid.nodes[1][1].center)
print(int(grid.nodes[2][2].center.x))
print(int(grid.nodes[TAILLE_Y-1][TAILLE_X-1].center.x))

print(len(grid.nodes), len(grid.nodes[0]))
for i in range(TAILLE_Y):
  for j in range(TAILLE_X):
    if labyrinthe[i, j] == MUR:
      grid.nodes[i][j].occupants.append(BoxCollider)




11 21
(11, 21)
0
Vector2D(x=1.5, y=1.5)
2
20
11 21


In [92]:
def dfs(grid):
  # Liste des cases déjà visitées initialisé vide
  cases_visitees = []
  chemin = []

  # Tant qu'on a des cases à visiter
  while cases_a_visiter:
    time.sleep(0.1)
    # Retire la première case à visiter
    # et l'ajoute dans les cases déjà visitées et le chemin trouvé
    case_courante = cases_a_visiter.pop()
    cases_visitees.insert(0, case_courante)
    chemin.append(case_courante)

    # Affiche la case courante dans le graph
    x = int(case_courante.center.x)
    y = int(case_courante.center.y)
    afficherLabyrinthe(labyrinthe.copy(), x, y, [c.center for c in cases_visitees])

    # Si on trouve la sortie on sort !
    if labyrinthe[y, x] == FIN:
      return True, chemin

    # Trouve des cases vide autour de la case courante
    # et les ajoute à la liste de case à visiter
    est_un_cul_de_sac = True

    cases_voisines = grid.get_node_neighbors(case_courante, allow_diagonal=False)
    
    for voisin in cases_voisines:
      if voisin.walkable and not voisin in cases_visitees:
        cases_a_visiter.append(voisin)
        est_un_cul_de_sac = False
        
    # Si on était dans un cul de sac, on enlève toutes cases jusqu'à la case à visiter
    while est_un_cul_de_sac:
      case_courante = chemin.pop()
      x = case_courante.center.x
      y = case_courante.center.y
      
      cases_voisines = grid.get_node_neighbors(case_courante, allow_diagonal=False)
      
      for voisin in cases_voisines:
        if voisin.walkable and not voisin in cases_visitees:
          est_un_cul_de_sac = False

      # la case courante fait partie du chemin
      if not est_un_cul_de_sac:
        chemin.append(case_courante)

  return False, chemin


# (y, x) pour grid
cases_a_visiter = [grid.nodes[1][1]]
status, chemin = dfs(grid)

# afficher le chemin trouvé
maze_copy = labyrinthe.copy()
for node in chemin:
  x = int(node.center.x)
  y = int(node.center.y)
  maze_copy[y, x] = CHEMIN
  afficherLabyrinthe(maze_copy, 0, 0, [])
    

In [ ]:
# Fonction qui trouve le chemin entre
# une case visitée et la case départ
def trouverChemin(cases_visitees, cases_precedentes, case_actuelle):
  chemin = []
  # Tant qu'on n'est pas rendu à la case départ (None)
  index_precedente = cases_visitees.index(case_actuelle)
  case_precedente = cases_precedentes[index_precedente]
  while case_precedente != None:
    # On ajoute la case précédente à la liste qui forme le chemin
    chemin.append(case_precedente)
    # On trouve l'index de la case précédente dans la listes de cases visitées
    index_precedente = cases_visitees.index(case_precedente)
    # On trouve la nouvelle case précédente dans la liste de cases précédentes
    case_precedente = cases_precedentes[index_precedente]

  # On retourne la liste de cases qui forme le chemin
  return chemin


def bfs(grid):
    cases_visitees = []
    cases_precedentes = []
    # liste de tuples cases & parents
    cases_a_visiter = [(grid.nodes[1][1], None)]
    
    while cases_a_visiter:
        time.sleep(0.1)
        case_courante = cases_a_visiter.pop(0)
        cases_visitees.insert(0, case_courante[0])
        cases_precedentes.insert(0, case_courante[1])
        
        # affiche la case courante dans la carte
        x = int(case_courante[0].center.x)
        y = int(case_courante[0].center.y)
        afficherLabyrinthe(labyrinthe.copy(), x, y, [c.center for c in cases_visitees])
        
        # Si on trouve la fin on sort ! 
        if labyrinthe[y, x] == FIN:
            chemin = trouverChemin(cases_visitees, cases_precedentes, case_courante[0])
            return True, chemin
        
        # Pour chaque voisins de la case actuelle
        cases_voisines = grid.get_node_neighbors(case_courante[0], allow_diagonal=False)
        
        for voisin in cases_voisines:
            if voisin.walkable and not voisin in cases_visitees:
                cases_a_visiter.append((voisin, case_courante[0]))
    
    return False, []
              
status, chemin = bfs(grid)

# afficher le chemin trouvé
maze_copy = labyrinthe.copy()
for node in chemin:
  x = int(node.center.x)
  y = int(node.center.y)
  maze_copy[y, x] = CHEMIN
  afficherLabyrinthe(maze_copy, 0, 0, [])
        
        

In [103]:
# Fonction qui estime le coût entre la position finale et la position courante
# Ici on le fait à vol d'oiseau
def heuristique(position, fin):
  pos_y = int(position.center.y)
  pos_x = int(position.center.x)
  fin_y = int(fin.center.y)
  fin_x = int(fin.center.x)
  # L'hypothénuse d'un triangle (c) est donnée par c² = a² + b²
  a2 = abs(fin_y - pos_y)
  b2 = abs(fin_x - pos_x)
  c2 = a2 + b2
  return np.sqrt(c2)

# Fonction qui calcul le coût d'une case
def fonctionDeCout(cout_actuel, cout_estime):
  # La fonction de cout est le cout actuel + le cout estimé par heuristique
  return cout_actuel + cout_estime

def rechercheHeuristiqueAStar(grid, debut, fin):
  # Initialisation des listes
  cases_a_visiter = [(debut, None)]
  cases_visitees = []
  cases_precedentes = []

  # Tant qu'on a des cases à visiter
  while cases_a_visiter:

    # S'il faut choisir entre deux cases à visiter
    if len(cases_a_visiter) > 1:
      couts_de_deplacement = []
      # Pour chaque case potentielle à visiter, on calcule le coût.
      for case_potentielle in cases_a_visiter:
        # Le cout actuel est le nombre de déplacement depuis la case départ.
        # Bref la longueur du chemin parcouru entre la case actuel et la case départ.
        chemin = trouverChemin(cases_visitees, cases_precedentes, case_potentielle[1])
        cout_actuel = len(chemin) + 1 # comptant la case potentielle
        cout_estime = heuristique(case_potentielle[0], fin)
        couts_de_deplacement.append(fonctionDeCout(cout_actuel, cout_estime))

      # Choisir le minimum dans la liste de couts de déplacement
      index_cout_min = couts_de_deplacement.index(min(couts_de_deplacement))
      case_courante = cases_a_visiter.pop(index_cout_min)

    # Sinon il n'y a qu'une case à visiter
    else:
      case_courante = cases_a_visiter.pop()

    # On ajoute la case courante aux listes des cases visitées et précédentes
    cases_visitees.insert(0, case_courante[0])
    cases_precedentes.insert(0, case_courante[1])

    # Affiche la case courante dans le graph
    y = int(case_courante[0].center.y)
    x = int(case_courante[0].center.x)
    afficherLabyrinthe(labyrinthe.copy(), x, y, [c.center for c in cases_visitees])

    # Si on trouve la sortie on sort !
    if labyrinthe[y, x] == FIN:
      return True, trouverChemin(cases_visitees, cases_precedentes, case_courante[0])

    # Pour chaque case voisine
    cases_voisines = grid.get_node_neighbors(case_courante[0], allow_diagonal=False)
    
    for voisin in cases_voisines:
      if voisin.walkable and voisin not in cases_visitees:
        cases_a_visiter.append((voisin, case_courante[0]))
        

  return False, []

# Orde (y, x) pour numpy et None pour indiquer que c'est le départ
debut = grid.nodes[1][1]
fin = grid.nodes[TAILLE_Y - 2][TAILLE_X - 2]

# La fonction rechercheHeuristiqueAStar(labyrinthe, debut, fin)
# retourne un status si la sortie a été trouvé ainsi que la liste de case
# qu'il faut prendre pour se rendre à la sortie.
status, chemin = rechercheHeuristiqueAStar(grid, debut, fin)

# Afficher le chemin trouvé
maze_copy = labyrinthe.copy()
for node in chemin:
  x = int(node.center.x)
  y = int(node.center.y)
  maze_copy[y, x] = CHEMIN
  afficherLabyrinthe(maze_copy, 0, 0, [])
    

# Breadth first search

In [2]:
# maze_string = '<br>'.join(''.join(row) for row in labyrinthe)
# display(HTML(f'''
#     <div id="maze" style="font-family: monospace; white-space: pre; line-height: 1.2;">
#     {maze_string}
#     </div>
#     <script>
#     document.getElementById('maze').innerHTML = `{maze_string}`;
#     </script>
#     '''))

def rechercheLargeurDabord(labyrinthe):
  # Liste des cases déjà visitées initialisé vide
  cases_visitees = []
  cases_precedentes = []

  # Tant qu'on a des cases à visiter
  while cases_a_visiter:
    time.sleep(0.1)
    # Retire la première case à visiter
    # et l'ajoute dans les cases déjà visitées
    case_courante = cases_a_visiter.pop(0)
    cases_visitees.insert(0, case_courante[0])
    cases_precedentes.insert(0, case_courante[1])

    # Affiche la case courante dans le graph
    y, x = case_courante[0][0], case_courante[0][1]
    afficherLabyrinthe(labyrinthe.copy(), x, y, cases_visitees)

    # Si on trouve la sortie on sort !
    if labyrinthe[y, x] == FIN:
      return True, cases_visitees, cases_precedentes

    # Trouve des cases vide autour de la case courante
    # et les ajoute à la liste de case à visiter

    # NORD
    # print("Y a t'il une case vide au nord ? ", labyrinthe[y-1, x] == VIDE)
    if labyrinthe[y-1, x] in [VIDE, FIN] and not (y-1, x) in cases_visitees:
      cases_a_visiter.append(((y-1, x), (y, x)))

    # SUD
    # print("Y a t'il une case vide au sud ? ", labyrinthe[y+1, x] == VIDE)
    if labyrinthe[y+1, x] in [VIDE, FIN] and not (y+1, x) in cases_visitees:
      cases_a_visiter.append(((y+1, x), (y, x)))

    # EST
    # print("Y a t'il une case vide à l'est ? ", labyrinthe[y, x+1] == VIDE)
    if labyrinthe[y, x+1] in [VIDE, FIN] and not (y, x+1) in cases_visitees:
      cases_a_visiter.append(((y, x+1), (y, x)))

    # OUEST
    # print("Y a t'il une case vide à l'ouest ? ", labyrinthe[y, x-1] == VIDE)
    if labyrinthe[y, x-1] in [VIDE, FIN] and not (y, x-1) in cases_visitees:
      cases_a_visiter.append(((y, x-1), (y, x)))

    # Debug
    # print('Marqueur ', case_courante)
    # print("Cases visitées ", cases_visitees)
    # print("Cases précédentes ", cases_precedentes)
    # print("Cases à visiter ", cases_a_visiter)
    # print("# - - - - - - - - - - - - - - - - - - - #")

  return False, cases_visitees, cases_precedentes

# Contient la position de la case de départ ainsi que sont parent
# Orde (y, x) pour numpy et None pour indiquer que c'est le départ
cases_a_visiter = [((1, 1), None)]

# La fonction rechercheLargeurDabord(labyrinthe) retourne un status si la sortie a été trouvée.
status, cases_visitees, cases_precedentes = rechercheLargeurDabord(labyrinthe)

# What's the path ?
chemin = []
case_precedente = cases_precedentes[0]
while case_precedente != None:
  chemin.append(case_precedente)
  index_precedente = cases_visitees.index(case_precedente)
  case_precedente = cases_precedentes[index_precedente]

# afficher le chemin trouvé
maze_copy = labyrinthe.copy()
for (y, x) in chemin:
  maze_copy[y, x] = CHEMIN
  afficherLabyrinthe(maze_copy, 0, 0, [])


# Depth first search

In [ ]:
maze_string = '<br>'.join(''.join(row) for row in labyrinthe)
display(HTML(f'''
    <div id="maze" style="font-family: monospace; white-space: pre; line-height: 1.2;">
    {maze_string}
    </div>
    <script>
    document.getElementById('maze').innerHTML = `{maze_string}`;
    </script>
    '''))

def rechercheProfondeurDabord(labyrinthe):
  # Liste des cases déjà visitées initialisé vide
  cases_visitees = []
  chemin = []

  # Tant qu'on a des cases à visiter
  while cases_a_visiter:
    time.sleep(0.1)
    # Retire la première case à visiter
    # et l'ajoute dans les cases déjà visitées et le chemin trouvé
    case_courante = cases_a_visiter.pop()
    cases_visitees.insert(0, case_courante)
    chemin.append(case_courante)

    # Affiche la case courante dans le graph
    y, x = case_courante[0], case_courante[1]
    afficherLabyrinthe(labyrinthe.copy(), x, y, cases_visitees)

    # Si on trouve la sortie on sort !
    if labyrinthe[y, x] == FIN:
      return True, chemin

    # Trouve des cases vide autour de la case courante
    # et les ajoute à la liste de case à visiter
    est_un_cul_de_sac = True

    # NORD
    # print("Y a t'il une case vide au nord ? ", labyrinthe[y-1, x] == VIDE)
    if labyrinthe[y-1, x] in [VIDE, FIN] and not (y-1, x) in cases_visitees:
      cases_a_visiter.append((y-1, x))
      est_un_cul_de_sac = False

    # SUD
    # print("Y a t'il une case vide au sud ? ", labyrinthe[y+1, x] == VIDE)
    if labyrinthe[y+1, x] in [VIDE, FIN] and not (y+1, x) in cases_visitees:
      cases_a_visiter.append((y+1, x))
      est_un_cul_de_sac = False

    # EST
    # print("Y a t'il une case vide à l'est ? ", labyrinthe[y, x+1] == VIDE)
    if labyrinthe[y, x+1] in [VIDE, FIN] and not (y, x+1) in cases_visitees:
      cases_a_visiter.append((y, x+1))
      est_un_cul_de_sac = False

    # OUEST
    # print("Y a t'il une case vide à l'ouest ? ", labyrinthe[y, x-1] == VIDE)
    if labyrinthe[y, x-1] in [VIDE, FIN] and not (y, x-1) in cases_visitees:
      cases_a_visiter.append((y, x-1))
      est_un_cul_de_sac = False

    # Si on était dans un cul de sac, on enlève toutes cases jusqu'à la case à visiter
    while est_un_cul_de_sac:
      case_courante = chemin.pop()
      y, x = case_courante[0], case_courante[1]

      # NORD
      if (y-1, x) in cases_a_visiter:
        est_un_cul_de_sac = False
      # SUD
      if (y+1, x) in cases_a_visiter:
        est_un_cul_de_sac = False
      # EST
      if (y, x+1) in cases_a_visiter:
        est_un_cul_de_sac = False
      # OUEST
      if (y, x-1) in cases_a_visiter:
        est_un_cul_de_sac = False

      # la case courante fait partie du chemin
      if not est_un_cul_de_sac:
        case_courante = chemin.append(case_courante)

    # Debuggage
    # print('Marqueur ', case_courante)
    # print("Cases visitées ", cases_visitees)
    # print("Cases à visiter ", cases_a_visiter)
    # print("# - - - - - - - - - - - - - - - - - - - #")

  return False, chemin


# (y, x) pour numpy
cases_a_visiter = [(1, 1)]
status, chemin = rechercheProfondeurDabord(labyrinthe)

# afficher le chemin trouvé
maze_copy = labyrinthe.copy()
for (y, x) in chemin:
  maze_copy[y, x] = CHEMIN
  afficherLabyrinthe(maze_copy, 0, 0, [])


# Recherche avec heuristique A* (A star) !

In [ ]:
maze_string = '<br>'.join(''.join(row) for row in labyrinthe)
display(HTML(f'''
    <div id="maze" style="font-family: monospace; white-space: pre; line-height: 1.2;">
    {maze_string}
    </div>
    <script>
    document.getElementById('maze').innerHTML = `{maze_string}`;
    </script>
    '''))


# Fonction qui trouve le chemin entre
# une case visitée et la case départ
def trouverChemin(cases_visitees, cases_precedentes, case_actuelle):
  chemin = []
  # Tant qu'on n'est pas rendu à la case départ (None)
  index_precedente = cases_visitees.index(case_actuelle)
  case_precedente = cases_precedentes[index_precedente]
  while case_precedente != None:
    # On ajoute la case précédente à la liste qui forme le chemin
    chemin.append(case_precedente)
    # On trouve l'index de la case précédente dans la listes de cases visitées
    index_precedente = cases_visitees.index(case_precedente)
    # On trouve la nouvelle case précédente dans la liste de cases précédentes
    case_precedente = cases_precedentes[index_precedente]

  # On retourne la liste de cases qui forme le chemin
  return chemin


# Fonction qui estime le coût entre la position finale et la position courante
# Ici on le fait à vol d'oiseau
def heuristique(position, fin):
  pos_y, pos_x = position
  fin_y, fin_x = fin
  # L'hypothénuse d'un triangle (c) est donnée par c² = a² + b²
  a2 = abs(fin_y - pos_y)
  b2 = abs(fin_x - pos_x)
  c2 = a2 + b2
  return np.sqrt(c2)

# Fonction qui calcul le coût d'une case
def fonctionDeCout(cout_actuel, cout_estime):
  # La fonction de cout est le cout actuel + le cout estimé par heuristique
  return cout_actuel + cout_estime

def rechercheHeuristiqueAStar(labyrinthe, debut, fin):
  # Initialisation des listes
  cases_a_visiter = [(debut, None)]
  cases_visitees = []
  cases_precedentes = []

  # Tant qu'on a des cases à visiter
  while cases_a_visiter:
    time.sleep(0.1)

    # S'il faut choisir entre deux cases à visiter
    if len(cases_a_visiter) > 1:
      couts_de_deplacement = []
      # Pour chaque case potentielle à visiter, on calcule le coût.
      for case_potentielle in cases_a_visiter:
        # Le cout actuel est le nombre de déplacement depuis la case départ.
        # Bref la longueur du chemin parcouru entre la case actuel et la case départ.
        chemin = trouverChemin(cases_visitees, cases_precedentes, case_potentielle[1])
        cout_actuel = len(chemin) + 1 # comptant la case potentielle
        cout_estime = heuristique(case_potentielle[0], (-2,-2))
        couts_de_deplacement.append(fonctionDeCout(cout_actuel, cout_estime))

      # Choisir le minimum dans la liste de couts de déplacement
      index_cout_min = couts_de_deplacement.index(min(couts_de_deplacement))
      case_courante = cases_a_visiter.pop(index_cout_min)

    # Sinon il n'y a qu'une case à visiter
    else:
      case_courante = cases_a_visiter.pop()

    # On ajoute la case courante aux listes des cases visitées et précédentes
    cases_visitees.insert(0, case_courante[0])
    cases_precedentes.insert(0, case_courante[1])

    # Affiche la case courante dans le graph
    y, x = case_courante[0][0], case_courante[0][1]
    afficherLabyrinthe(labyrinthe.copy(), x, y, cases_visitees)

    # Si on trouve la sortie on sort !
    if labyrinthe[y, x] == FIN:
      return True, trouverChemin(cases_visitees, cases_precedentes, (y, x))

    # Trouve des cases vide autour de la case courante
    # et les ajoute à la liste de case à visiter

    # NORD
    # print("Y a t'il une case vide au nord ? ", labyrinthe[y-1, x] == VIDE)
    if labyrinthe[y-1, x] in [VIDE, FIN] and not (y-1, x) in cases_visitees:
      cases_a_visiter.append(((y-1, x), (y, x)))

    # SUD
    # print("Y a t'il une case vide au sud ? ", labyrinthe[y+1, x] == VIDE)
    if labyrinthe[y+1, x] in [VIDE, FIN] and not (y+1, x) in cases_visitees:
      cases_a_visiter.append(((y+1, x), (y, x)))

    # EST
    # print("Y a t'il une case vide à l'est ? ", labyrinthe[y, x+1] == VIDE)
    if labyrinthe[y, x+1] in [VIDE, FIN] and not (y, x+1) in cases_visitees:
      cases_a_visiter.append(((y, x+1), (y, x)))

    # OUEST
    # print("Y a t'il une case vide à l'ouest ? ", labyrinthe[y, x-1] == VIDE)
    if labyrinthe[y, x-1] in [VIDE, FIN] and not (y, x-1) in cases_visitees:
      cases_a_visiter.append(((y, x-1), (y, x)))

    # Debug
    # print('Marqueur ', case_courante)
    # print("Cases visitées ", cases_visitees)# afficher le chemin trouvé
    # print("Cases précédentes ", cases_precedentes)
    # print("Cases à visiter ", cases_a_visiter)
    # print("# - - - - - - - - - - - - - - - - - - - #")

  return False, []

# Orde (y, x) pour numpy et None pour indiquer que c'est le départ
debut = (1, 1)
fin = (TAILLE_Y - 2, TAILLE_X - 2)

# La fonction rechercheHeuristiqueAStar(labyrinthe, debut, fin)
# retourne un status si la sortie a été trouvé ainsi que la liste de case
# qu'il faut prendre pour se rendre à sortie.
status, chemin = rechercheHeuristiqueAStar(labyrinthe, debut, fin)

# afficher le chemin trouvé
maze_copy = labyrinthe.copy()
for (y, x) in chemin:
  maze_copy[y, x] = CHEMIN
  afficherLabyrinthe(maze_copy, 0, 0, [])



