# Qu'est-ce que la recherche de trajets ?

C'est la recherche d'un trajet qui permet d'aller d'un point A à un point B au travers d'une carte. Dans nos exemples, nous utiliseront les cartes cartésiennes en 2 dimensions, X et Y.

// insert image of maps

# Représantation d'une carte 2D en python

Il est possible de représenter une carte 2D comme un tableau de valeurs en python. Par exemple une carte de 10 en Y à la verticale et 10 en X à l'horizontal peut facilement être écrite en python comme suit:



In [ ]:
import numpy as np

# Ici, Y est en premier et X est en deuxième
carte = np.zeros((11, 11))
print(carte)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Par la suite on peut manuellement ajouter des information pour chaque point en changeant des informations contenu dans le tableau. Par exemple, si on veut dire que le point de départ est à Y = 0 et X = 0 on peut assigner la valeur 1 comme suit:

In [ ]:
carte[0, 0] = 1
print(carte)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Si on veut ajouter un point d'arrivé à Y = 7, X = 9, on peut assigner la valeur 2 comme suit:

In [ ]:
carte[7, 9] = 2
print(carte)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Si on veut ajouter des obstacles dans la colone du centre de la carte, on peut assigner la valeur 3 comme suit:

In [ ]:
carte[:, 5] = 3
print(carte)

[[1. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]]


De même que si on veut ajouter des obstacles dans la ligne du centre, on peut assigner la valeur 3 comme suit:

In [ ]:
carte[5, :] = 3
print(carte)

[[1. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]]


Maintenant si on veut ajouter des obstacles aléatoires dans la carte, on peut assigner la valeur 4 comme suit:

In [ ]:
# Il se peut que l'obstacle aléatoire soit par dessus un autre dans la carte
random_Y = np.random.randint(0, 11)
random_X = np.random.randint(0, 11)
carte[random_Y, random_X] = 4
print(carte)

[[5. 0. 0. 0. 5. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [3. 4. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [0. 0. 0. 0. 5. 3. 0. 0. 0. 0. 0.]
 [0. 5. 0. 5. 0. 3. 0. 0. 0. 2. 0.]
 [5. 5. 0. 0. 5. 3. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 3. 0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]]


Dans si on veut en ajouter 10 obstacles avec la valeur 5 ça donne :

In [ ]:
for i in range(10):
    random_Y = np.random.randint(0, 11)
    random_X = np.random.randint(0, 11)
    carte[random_Y, random_X] = 5
print(carte)

[[5. 0. 0. 0. 5. 3. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 3. 0. 5. 0. 3. 5.]
 [0. 0. 5. 5. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 3. 0. 0. 0. 0. 5.]
 [3. 4. 3. 3. 3. 3. 5. 3. 3. 3. 3.]
 [0. 0. 0. 0. 5. 3. 0. 0. 0. 0. 0.]
 [0. 5. 0. 5. 0. 3. 0. 0. 0. 2. 0.]
 [5. 5. 0. 0. 5. 3. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 3. 0. 5. 0. 5. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]]


# ❗ RAPPEL : Peut-on ajouter ou lire une valeur à l'index 11, 11 ?

In [ ]:
carte[10, 10] = 3
print(carte[10, 10])

IndexError: index 10 is out of bounds for axis 0 with size 10

# Crée ton labyrinthe!

In [16]:
# based on https://inventwithpython.com/recursion/chapter11.html
import numpy as np
from IPython.display import HTML, display
import time

# Défini la taille du labyrinthe minimum 3x3 et impair
TAILLE_Y = 11
TAILLE_X = 21

assert TAILLE_Y % 2 == 1 and TAILLE_Y >= 3
assert TAILLE_X % 2 == 1 and TAILLE_X >= 3

# Permet de regénérer le même labyrinthe
import random
# SEED = 2
# random.seed(SEED)

VIDE = ' '
MUR = '█'
DEBUT = 'D'
FIN = 'F'
PACMAN = 'c'
NORD, SUD, EST, OUEST = 'n', 's', 'e', 'o'

labyrinthe = np.full((TAILLE_Y, TAILLE_X), MUR)

maze_string = '<br>'.join(''.join(row) for row in labyrinthe)
display(HTML(f'''
    <div id="maze" style="font-family: monospace; white-space: pre; line-height: 1.2;">
    {maze_string}
    </div>
    <script>
    document.getElementById('maze').innerHTML = `{maze_string}`;
    </script>
    '''))

def printLabyrinthe(maze, x, y):
    if (x, y) != (0, 0):
      maze[y, x] = PACMAN
    maze_string = '<br>'.join(''.join(row) for row in maze)

    html = f'''
    <script>
    document.getElementById('maze').innerHTML = `{maze_string}`;
    </script>
    '''

    display(HTML(html))
    time.sleep(0.1)


def faireChemin(x, y):
  """Carve out" empty spaces in the maze at x, y and then
    recursively move to neighboring unvisited spaces. This
    function backtracks when the mark has reached a dead end."""
  labyrinthe[y, x] = VIDE
  printLabyrinthe(labyrinthe.copy(), x, y)

  voisins_non_visites = []
  while True:
    if y > 1 and (x, y - 2) not in chemin_visites:
      voisins_non_visites.append(NORD)
    if y < TAILLE_Y - 2 and (x, y + 2) not in chemin_visites:
      voisins_non_visites.append(SUD)
    if x < TAILLE_X - 2 and (x + 2, y) not in chemin_visites:
      voisins_non_visites.append(EST)
    if x > 1 and (x - 2, y) not in chemin_visites:
      voisins_non_visites.append(OUEST)


    if len(voisins_non_visites) == 0:
      # dead end
      break
    else:
      # Recursion
      prochain_noeud = random.choice(voisins_non_visites)
      if prochain_noeud == NORD:
        labyrinthe[y - 1, x] = VIDE
        y -= 2
      elif prochain_noeud == SUD:
        labyrinthe[y + 1, x] = VIDE
        y += 2
      elif prochain_noeud == EST:
        labyrinthe[y, x + 1] = VIDE
        x += 2
      elif prochain_noeud == OUEST:
        labyrinthe[y, x - 1] = VIDE
        x -= 2
      chemin_visites.append((x, y))
      voisins_non_visites = []
      faireChemin(x, y)


chemin_visites = [(1, 1)]
faireChemin(1, 1)

labyrinthe[1, 1] = DEBUT
labyrinthe[-2, -2] = FIN
printLabyrinthe(labyrinthe.copy(), 0, 0)


# Depth first search

In [17]:
maze_string = '<br>'.join(''.join(row) for row in labyrinthe)
display(HTML(f'''
    <div id="maze" style="font-family: monospace; white-space: pre; line-height: 1.2;">
    {maze_string}
    </div>
    <script>
    document.getElementById('maze').innerHTML = `{maze_string}`;
    </script>
    '''))

def rechercheLargeurDabord(labyrinthe):
  # Liste des cases déjà visitées initialisé vide
  cases_visitees = []
  cases_precedentes = []

  # Tant qu'on a des cases à visiter
  while cases_a_visiter:
    time.sleep(0.1)
    # Retire la première case à visiter
    # et l'ajoute dans les cases déjà visitées
    case_courante = cases_a_visiter.pop(0)
    cases_visitees.insert(0, case_courante[0])
    cases_precedentes.insert(0, case_courante[1])

    # Affiche la case courante dans le graph
    y, x = case_courante[0][0], case_courante[0][1]
    printLabyrinthe(labyrinthe.copy(), x, y)

    # Si on trouve la sortie on sort !
    if labyrinthe[y, x] == FIN:
      return True, cases_visitees, cases_precedentes

    # Trouve des cases vide autour de la case courante
    # et les ajoute à la liste de case à visiter

    # NORD
    # print("Y a t'il une case vide au nord ? ", labyrinthe[y-1, x] == VIDE)
    if labyrinthe[y-1, x] in [VIDE, FIN] and not (y-1, x) in cases_visitees:
      cases_a_visiter.append(((y-1, x), (y, x)))

    # SUD
    # print("Y a t'il une case vide au sud ? ", labyrinthe[y+1, x] == VIDE)
    if labyrinthe[y+1, x] in [VIDE, FIN] and not (y+1, x) in cases_visitees:
      cases_a_visiter.append(((y+1, x), (y, x)))

    # EST
    # print("Y a t'il une case vide à l'est ? ", labyrinthe[y, x+1] == VIDE)
    if labyrinthe[y, x+1] in [VIDE, FIN] and not (y, x+1) in cases_visitees:
      cases_a_visiter.append(((y, x+1), (y, x)))

    # OUEST
    # print("Y a t'il une case vide à l'ouest ? ", labyrinthe[y, x-1] == VIDE)
    if labyrinthe[y, x-1] in [VIDE, FIN] and not (y, x-1) in cases_visitees:
      cases_a_visiter.append(((y, x-1), (y, x)))

    # Debug
    # print('Marqueur ', case_courante)
    # print("Cases visitées ", cases_visitees)
    # print("Cases précédentes ", cases_precedentes)
    # print("Cases à visiter ", cases_a_visiter)
    # print("# - - - - - - - - - - - - - - - - - - - #")

  return False, cases_visitees, cases_precedentes

# Contient la position de la case de départ ainsi que sont parent
# Orde (y, x) pour numpy et None pour indiquer que c'est le départ
cases_a_visiter = [((1, 1), None)]

# La fonction rechercheLargeurDabord(labyrinthe) retourne un status si la sortie a été trouvée.
status, cases_visitees, cases_precedentes = rechercheLargeurDabord(labyrinthe)

# What's the path ?
chemin = []
case_precedente = cases_precedentes[0]
while case_precedente != None:
  chemin.append(case_precedente)
  index_precedente = cases_visitees.index(case_precedente)
  case_precedente = cases_precedentes[index_precedente]

# afficher le chemin trouvé
for (y, x) in chemin:
  labyrinthe[y, x] = '·'
  printLabyrinthe(labyrinthe.copy(), 0, 0)


In [ ]:
maze_string = '<br>'.join(''.join(row) for row in labyrinthe)
display(HTML(f'''
    <div id="maze" style="font-family: monospace; white-space: pre; line-height: 1.2;">
    {maze_string}
    </div>
    <script>
    document.getElementById('maze').innerHTML = `{maze_string}`;
    </script>
    '''))

def rechercheProfondeurDabord(labyrinthe):
  # Liste des cases déjà visitées initialisé vide
  cases_visitees = []
  chemin = []

  # Tant qu'on a des cases à visiter
  while cases_a_visiter:
    time.sleep(0.1)
    # Retire la première case à visiter
    # et l'ajoute dans les cases déjà visitées et le chemin trouvé
    case_courante = cases_a_visiter.pop()
    cases_visitees.insert(0, case_courante)
    chemin.append(case_courante)

    # Affiche la case courante dans le graph
    y, x = case_courante[0], case_courante[1]
    printLabyrinthe(labyrinthe.copy(), x, y)

    # Si on trouve la sortie on sort !
    if labyrinthe[y, x] == FIN:
      return True, chemin

    # Trouve des cases vide autour de la case courante
    # et les ajoute à la liste de case à visiter
    est_un_cul_de_sac = True

    # NORD
    # print("Y a t'il une case vide au nord ? ", labyrinthe[y-1, x] == VIDE)
    if labyrinthe[y-1, x] in [VIDE, FIN] and not (y-1, x) in cases_visitees:
      cases_a_visiter.append((y-1, x))
      est_un_cul_de_sac = False

    # SUD
    # print("Y a t'il une case vide au sud ? ", labyrinthe[y+1, x] == VIDE)
    if labyrinthe[y+1, x] in [VIDE, FIN] and not (y+1, x) in cases_visitees:
      cases_a_visiter.append((y+1, x))
      est_un_cul_de_sac = False

    # EST
    # print("Y a t'il une case vide à l'est ? ", labyrinthe[y, x+1] == VIDE)
    if labyrinthe[y, x+1] in [VIDE, FIN] and not (y, x+1) in cases_visitees:
      cases_a_visiter.append((y, x+1))
      est_un_cul_de_sac = False

    # OUEST
    # print("Y a t'il une case vide à l'ouest ? ", labyrinthe[y, x-1] == VIDE)
    if labyrinthe[y, x-1] in [VIDE, FIN] and not (y, x-1) in cases_visitees:
      cases_a_visiter.append((y, x-1))
      est_un_cul_de_sac = False

    # Si on était dans un cul de sac, on enlève toutes cases jusqu'à la case à visiter
    while est_un_cul_de_sac:
      case_courante = chemin.pop()
      y, x = case_courante[0], case_courante[1]

      # NORD
      if (y-1, x) in cases_a_visiter:
        est_un_cul_de_sac = False
      # SUD
      if (y+1, x) in cases_a_visiter:
        est_un_cul_de_sac = False
      # EST
      if (y, x+1) in cases_a_visiter:
        est_un_cul_de_sac = False
      # OUEST
      if (y, x-1) in cases_a_visiter:
        est_un_cul_de_sac = False

      # la case courante fait partie du chemin
      if not est_un_cul_de_sac:
        case_courante = chemin.append(case_courante)

    # Debuggage
    # print('Marqueur ', case_courante)
    # print("Cases visitées ", cases_visitees)
    # print("Cases à visiter ", cases_a_visiter)
    # print("# - - - - - - - - - - - - - - - - - - - #")

  return False, chemin


# (y, x) pour numpy
cases_a_visiter = [(1, 1)]
status, chemin = rechercheProfondeurDabord(labyrinthe)

# afficher le chemin trouvé?
for (y, x) in chemin:
  labyrinthe[y, x] = '·'
  printLabyrinthe(labyrinthe.copy(), 0, 0)


# Recherche avec heuristique A* (A star) !

In [11]:
maze_string = '<br>'.join(''.join(row) for row in labyrinthe)
display(HTML(f'''
    <div id="maze" style="font-family: monospace; white-space: pre; line-height: 1.2;">
    {maze_string}
    </div>
    <script>
    document.getElementById('maze').innerHTML = `{maze_string}`;
    </script>
    '''))


# Fonction qui trouve le chemin entre
# une case visitée et la case départ
def trouverChemin(cases_visitees, cases_precedentes, case_actuelle):
  chemin = []
  # Tant qu'on n'est pas rendu à la case départ (None)
  index_precedente = cases_visitees.index(case_actuelle)
  case_precedente = cases_precedentes[index_precedente]
  while case_precedente != None:
    # On ajoute la case précédente à la liste qui forme le chemin
    chemin.append(case_precedente)
    # On trouve l'index de la case précédente dans la listes de cases visitées
    index_precedente = cases_visitees.index(case_precedente)
    # On trouve la nouvelle case précédente dans la liste de cases précédentes
    case_precedente = cases_precedentes[index_precedente]

  # On retourne la liste de cases qui forme le chemin
  return chemin


# Fonction qui estime le coût entre la position finale et la position courante
# Ici on le fait à vol d'oiseau
def heuristique(position, fin):
  pos_y, pos_x = position
  fin_y, fin_x = fin
  # L'hypothénuse d'un triangle (c) est donnée par c² = a² + b²
  a2 = abs(fin_y - pos_y)
  b2 = abs(fin_x - pos_x)
  c2 = a2 + b2
  return np.sqrt(c2)

# Fonction qui calcul le coût d'une case
def fonctionDeCout(cout_actuel, cout_estime):
  # La fonction de cout est le cout actuel + le cout estimé par heuristique
  return cout_actuel + cout_estime

def rechercheHeuristiqueAStar(labyrinthe, debut, fin):
  # Initialisation des listes
  cases_a_visiter = [(debut, None)]
  cases_visitees = []
  cases_precedentes = []

  # Tant qu'on a des cases à visiter
  while cases_a_visiter:
    time.sleep(0.1)

    # S'il faut choisir entre deux cases à visiter
    if len(cases_a_visiter) > 1:
      couts_de_deplacement = []
      # Pour chaque case potentielle à visiter, on calcule le coût.
      for case_potentielle in cases_a_visiter:
        # Le cout actuel est le nombre de déplacement depuis la case départ.
        # Bref la longueur du chemin parcouru entre la case actuel et la case départ.
        chemin = trouverChemin(cases_visitees, cases_precedentes, case_potentielle[1])
        cout_actuel = len(chemin) + 1 # comptant la case potentielle
        cout_estime = heuristique(case_potentielle[0], (-2,-2))
        couts_de_deplacement.append(fonctionDeCout(cout_actuel, cout_estime))

      # Choisir le minimum dans la liste de couts de déplacement
      index_cout_min = couts_de_deplacement.index(min(couts_de_deplacement))
      case_courante = cases_a_visiter.pop(index_cout_min)

    # Sinon il n'y a qu'une case à visiter
    else:
      case_courante = cases_a_visiter.pop()

    # On ajoute la case courante aux listes des cases visitées et précédentes
    cases_visitees.insert(0, case_courante[0])
    cases_precedentes.insert(0, case_courante[1])

    # Affiche la case courante dans le graph
    y, x = case_courante[0][0], case_courante[0][1]
    printLabyrinthe(labyrinthe.copy(), x, y)

    # Si on trouve la sortie on sort !
    if labyrinthe[y, x] == FIN:
      return True, trouverChemin(cases_visitees, cases_precedentes, (y, x))

    # Trouve des cases vide autour de la case courante
    # et les ajoute à la liste de case à visiter

    # NORD
    # print("Y a t'il une case vide au nord ? ", labyrinthe[y-1, x] == VIDE)
    if labyrinthe[y-1, x] in [VIDE, FIN] and not (y-1, x) in cases_visitees:
      cases_a_visiter.append(((y-1, x), (y, x)))

    # SUD
    # print("Y a t'il une case vide au sud ? ", labyrinthe[y+1, x] == VIDE)
    if labyrinthe[y+1, x] in [VIDE, FIN] and not (y+1, x) in cases_visitees:
      cases_a_visiter.append(((y+1, x), (y, x)))

    # EST
    # print("Y a t'il une case vide à l'est ? ", labyrinthe[y, x+1] == VIDE)
    if labyrinthe[y, x+1] in [VIDE, FIN] and not (y, x+1) in cases_visitees:
      cases_a_visiter.append(((y, x+1), (y, x)))

    # OUEST
    # print("Y a t'il une case vide à l'ouest ? ", labyrinthe[y, x-1] == VIDE)
    if labyrinthe[y, x-1] in [VIDE, FIN] and not (y, x-1) in cases_visitees:
      cases_a_visiter.append(((y, x-1), (y, x)))

    # Debug
    # print('Marqueur ', case_courante)
    # print("Cases visitées ", cases_visitees)
    # print("Cases précédentes ", cases_precedentes)
    # print("Cases à visiter ", cases_a_visiter)
    # print("# - - - - - - - - - - - - - - - - - - - #")

  return False, []

# Orde (y, x) pour numpy et None pour indiquer que c'est le départ
debut = (1, 1)
fin = (TAILLE_Y - 2, TAILLE_X - 2)

# La fonction rechercheHeuristiqueAStar(labyrinthe, debut, fin)
# retourne un status si la sortie a été trouvé ainsi que la liste de case
# qu'il faut prendre pour se rendre à sortie.
status, chemin = rechercheHeuristiqueAStar(labyrinthe, debut, fin)

# afficher le chemin trouvé
for (y, x) in chemin:
  labyrinthe[y, x] = '·'
  printLabyrinthe(labyrinthe.copy(), 0, 0)



